name: guia_innat
description: Projeto Guia InNat em cordova convertido para versão Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.4+33506

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # ✅ UI Components - versões atualizadas
  auto_size_text: ^3.0.0
  flutter_animate: ^4.2.0  # Versão compatível
  font_awesome_flutter: ^10.4.0  # Versão compatível
  google_fonts: ^6.3.2
  
  # ✅ Navigation & State Management
  ## go_router: ^12.1.3  # Versão estável compatível
  go_router: ^12.1.3  # Versão estável compatível
  provider: ^6.1.5
  
  # ✅ Networking & Caching - otimizadas
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  cached_network_image_web: ^1.3.1
  flutter_cache_manager: ^3.4.1
  http: ^1.2.2
  
  # ✅ Storage & Persistence
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.13  # Versão compatível
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: ^2.4.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: ^2.4.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_foundation: ^2.4.1
  path_provider_linux: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.3.0
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  
  # ✅ Media & Images
  image_picker: ^1.0.7
  photo_view: ^0.15.0
  image: ^4.2.0
  media_store_plus: ^0.1.3
  
  # ✅ ML & AI
  tflite_flutter: ^0.11.0
  
  # ✅ Utils & Helpers
  collection: ^1.19.1
  from_css_color: ^2.0.0
  intl: ^0.20.2
  json_path: ^0.8.0
  page_transition: ^2.2.1
  permission_handler: ^12.0.1
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.20  # Versão compatível
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  uuid: ^4.5.1
  
  # ✅ Icons
  cupertino_icons: ^1.0.0
  rename: ^3.1.0

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/icons/app_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/models/
    # Estrutura de insetos parasitoides
    - assets/images/insetos/parasitoides/mosca_taquinidea/
    - assets/images/insetos/parasitoides/vespa_parasitoide/
    # Estrutura de insetos predadores
    - assets/images/insetos/predadores/aranhas/
    - assets/images/insetos/predadores/besouro_carabideo/
    - assets/images/insetos/predadores/crisopideo/
    - assets/images/insetos/predadores/joaninhas/
    - assets/images/insetos/predadores/libelulas/
    - assets/images/insetos/predadores/mosca_asilidea/
    - assets/images/insetos/predadores/mosca_dolicopodidea/
    - assets/images/insetos/predadores/mosca_sirfidea/
    - assets/images/insetos/predadores/percevejo_geocoris/
    - assets/images/insetos/predadores/percevejo_orius/
    - assets/images/insetos/predadores/percevejo_pentatomideo/
    - assets/images/insetos/predadores/percevejo_reduviideo/
    - assets/images/insetos/predadores/tesourinha/
    - assets/images/insetos/predadores/vespa_predadora/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
